export const EXAM_LIST_SELECT = {
  id: true,
  subject_id: true,
  type: true,
  title: true,
  status: true,
  rejection_reason: true,
  start_time: true,
  end_time: true,
  duration_minutes: true,
  difficulty_mix: true,
  points_per_question: true,
  target_scope: true,
  quiz_source: true,
  created_at: true,
  subject: { select: { id: true, code: true, name: true } },
  owner: { select: { id: true, full_name: true } },
  _count: { select: { pool_questions: true, student_exams: true } },
} as const;

export const EXAM_DETAIL_SELECT = {
  id: true,
  subject_id: true,
  type: true,
  created_by: true,
  owner_id: true,
  title: true,
  status: true,
  rejection_reason: true,
  approved_by: true,
  approved_at: true,
  access_code_expires_at: true,
  start_time: true,
  end_time: true,
  duration_minutes: true,
  difficulty_mix: true,
  points_per_question: true,
  target_scope: true,
  quiz_source: true,
  created_at: true,
  updated_at: true,
  subject: { select: { id: true, code: true, name: true } },
  owner: { select: { id: true, full_name: true } },
  pool_questions: {
    include: { question: { select: { id: true, text: true, difficulty: true, question_type: true, is_archived: true, options: true, correct_answer: true, grade: true, image_url: true } } },
  },
  target_sections: true,
  target_students: true,
} as const;

export const EXAM_SECRET_FIELDS = ['access_code_hash', 'access_code_encrypted'] as const;
